spring:
  profiles:
    active: live
    group:
      local: local_server, common, secret
      #      blue: blue_server, common, secret
      #      blue: green_server, common, secret
      live: live_server, common, secret

---

spring:
  config:
    activate:
      on-profile: local_server
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
server:
  port: 8080
react:
  server:
    protocol: http
    host: localhost
    port: 5173

---

spring:
  config:
    activate:
      on-profile: live_server
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://dreampath.store/login/oauth2/code/google
          naver:
            redirect-uri: https://dreampath.store/login/oauth2/code/naver
server:
  port: 8080
react:
  server:
    protocol: https
    host: dreampath.store
    port: 80

---

#spring:
#  config:
#    activate:
#      on-profile: blue_server
#server:
#  port: 8080
#react:
#  server:
#    protocol: https
#    host: ??? ?? ?? ??(ip ?? ???)
#    port: 5173

---

#spring:
#  config:
#    activate:
#      on-profile: green_server
#server:
#  port: 9090
#react:
#  server:
#    protocol: https
#    host: ??? ?? ?? ??(ip ?? ???)
#    port: 5173

---

spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 100MB #??? ??? ?? ?? ????
      max-request-size: 1000MB #??? ???? ???? ?? ? ?? ????
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - profile
              - email
          naver:
            client-name: NAVER
            authorization-grant-type: authorization_code
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations:
    - /mappers/*.xml
    - /mappers/user/*.xml
    - /mappers/post/*.xml
    - /mappers/point/*.xml
    - /mappers/ticket/*.xml
    - /mappers/mentoring_register/*.xml
    - /mappers/mentoring_comment/*.xml

springdoc:
  override-with-generic-response: false
  
server:
  forward-headers-strategy: native


schedule:
  cron: 0 0 0 * * *
  use: true